sudo: false

language: node_js

node_js: '8'

cache:
  directories:
    - ~/.npm

install: npm install

script:
  - npm run lint:commit:ci
  - npm run lint

after_success:
  - npx -p semantic-release@7 -c "semantic-release pre && npm publish && semantic-release post"

branches:
  only: master
